name: cocotradeerp
description: "CocoTrade ERP - Coconut Canvassing and Logistics Management Suite"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  permission_handler: ^11.3.1 
  encrypt: ^5.0.3
  file_selector: ^1.0.3
  pdf: ^3.11.1
  printing: ^5.13.2
  shared_preferences: ^2.3.2
  file_picker: ^8.1.4
  path_provider: ^2.1.4
  share_plus: ^10.0.2
  intl: ^0.19.0
  crypto: ^3.0.5
  window_manager: ^0.5.2
  qr_flutter: ^4.1.0
  mobile_scanner: ^5.1.1
  http: ^1.6.0
  googleapis: ^14.0.0
  url_launcher: ^6.3.2
  googleapis_auth: ^2.3.3
  google_sign_in: ^6.2.1
  extension_google_sign_in_as_googleapis_auth: ^2.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  msix: ^3.18.0

flutter:
  uses-material-design: true
  assets:
    - assets/icon.png

msix_config:
  display_name: CocoTrade ERP
  publisher_display_name: Sri Sai Coconuts
  identity_name: com.cocotrade.erp
  msix_version: 1.0.0.0
  logo_path: assets/icon.png
  make_appinstaller: true
  appinstaller_url: https://your-website.com/downloads